---
- name: My first play
  hosts: all
  become: true
 
  tasks:
  
  - name: Update and Upgrade
    apt:
      update_cache: true
      upgrade: dist

  - name: Install Apache
    apt:
      name: apache2
      state: latest
    
  - name: Ensure apache is running
    service:
      name: apache2
      state: started

    

     
      
