---
- name: My first play
  hosts: all
  become: true

  pre_tasks:
  - name: Update and Upgrade
    apt:
      clean: true
      update_cache: true
      upgrade: dist
      
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
    
  - name: Ensure apache is running
    service:
      name: apache2
      state: started

    

     
      
