name: Destroy infrastracture

on: workflow_dispatch

jobs:
  deploy:
    runs-on: cicd1
  

    steps:

      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Terraform Init
        run: terraform init

      - name: Create a tfvars file
        run: |
          echo "cf_email=\"${{ secrets.CF_EMAIL }}\"" > my_variables.tfvars
          echo "cf_api=\"${{ secrets.CF_API }}\"" >> my_variables.tfvars
          echo "zonecf_id=\"${{ secrets.ZONECF_ID }}\"" >> my_variables.tfvars
          echo "pub_key=\"${{ secrets.PUB_KEY }}\"" >> my_variables.tfvars

        # On push to "main", build or change infrastructure according to Terraform configuration files
        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var-file=my_variables.tfvars
